// db_part3.js - Espécies 401 a 500 para DendroKey
export const speciesDataPart3 = [
  {
    "id": "401",
    "scientificName": "Xylopia sericea",
    "popularNames": ["Pimenta-de-macaco-peluda"],
    "family": "Annonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Indumento seríceo prateado na face inferior.",
    "description": "Comum em matas de galeria."
  },
  {
    "id": "402",
    "scientificName": "Vochysia haenkeana",
    "popularNames": ["Querana"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Verticilada",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Nervura central proeminente, folhas verticiladas.",
    "description": "Cerrado e transição."
  },
  {
    "id": "403",
    "scientificName": "Andira fraxinifolia",
    "popularNames": ["Angelim-doce"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos oblongos, inflorescência roxa.",
    "description": "Mata Atlântica."
  },
  {
    "id": "404",
    "scientificName": "Melanoxylon brauna",
    "popularNames": ["Braúna"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Madeira negra muito dura.",
    "description": "Mata Atlântica."
  },
  {
    "id": "405",
    "scientificName": "Symphonia globulifera",
    "popularNames": ["Anani", "Bulandi"],
    "family": "Clusiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Amarelo (Látex)",
    "spines": false,
    "specialFeatures": "Látex amarelo abundante.",
    "description": "Zonas úmidas."
  },
  {
    "id": "406",
    "scientificName": "Trithrinax brasiliensis",
    "popularNames": ["Buriti-palito"],
    "family": "Arecaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Tronco coberto por espinhos entrelaçados.",
    "description": "Palmeira."
  },
  {
    "id": "407",
    "scientificName": "Nectandra grandiflora",
    "popularNames": ["Canela-amarela"],
    "family": "Lauraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas grandes com odor de canela.",
    "description": "Mata Atlântica."
  },
  {
    "id": "408",
    "scientificName": "Euplassa cantareirae",
    "popularNames": ["Carvalho-da-serra"],
    "family": "Proteaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas ferrugíneas, margem denteada.",
    "description": "Mata de altitude."
  },
  {
    "id": "409",
    "scientificName": "Senna spectabilis",
    "popularNames": ["Cássia-do-nordeste"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Paripinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flores amarelas intensas.",
    "description": "Ornamental e pioneira."
  },
  {
    "id": "410",
    "scientificName": "Cedrela odorata",
    "popularNames": ["Cedro-vermelho"],
    "family": "Meliaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Madeira com forte odor aromático.",
    "description": "Mata alta."
  },
  {
    "id": "411",
    "scientificName": "Sterculia striata",
    "popularNames": ["Chichá-do-cerrado"],
    "family": "Malvaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas grandes cordiformes, fruto vermelho.",
    "description": "Cerrado."
  },
  {
    "id": "412",
    "scientificName": "Ilex dumosa",
    "popularNames": ["Congonha-miúda"],
    "family": "Aquifoliaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas pequenas verde-escuras.",
    "description": "Beira de mata."
  },
  {
    "id": "413",
    "scientificName": "Cecropia glaziovii",
    "popularNames": ["Embaúba-vermelha"],
    "family": "Urticaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas peltadas com veias vermelhas.",
    "description": "Pioneira."
  },
  {
    "id": "414",
    "scientificName": "Eschweilera ovata",
    "popularNames": ["Embiriba"],
    "family": "Lecythidaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Casca fibrosa que se solta em tiras.",
    "description": "Mata Atlântica."
  },
  {
    "id": "415",
    "scientificName": "Alseis floribunda",
    "popularNames": ["Falsa-pelada"],
    "family": "Rubiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco liso com manchas claras.",
    "description": "Mata de galeria."
  },
  {
    "id": "416",
    "scientificName": "Albizia edwallii",
    "popularNames": ["Farinha-seca"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos muito pequenos, tronco esbranquiçado.",
    "description": "Pioneira."
  },
  {
    "id": "417",
    "scientificName": "Parkia gigantocarpa",
    "popularNames": ["Fava-barriguda"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Vagens gigantes pendentes.",
    "description": "Mata alta."
  },
  {
    "id": "418",
    "scientificName": "Casearia decandra",
    "popularNames": ["Guaçatunga-miúda"],
    "family": "Salicaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Pontuações translúcidas nas folhas.",
    "description": "Mata."
  },
  {
    "id": "419",
    "scientificName": "Esenbeckia leiocarpa",
    "popularNames": ["Guarantã"],
    "family": "Rutaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas com glândulas oleíferas (cheiro cítrico).",
    "description": "Madeira de lei."
  },
  {
    "id": "420",
    "scientificName": "Maytenus robusta",
    "popularNames": ["Guarapoca"],
    "family": "Celastraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas rígidas, casca escura.",
    "description": "Mata Seca."
  },
  {
    "id": "421",
    "scientificName": "Vochysia magnifica",
    "popularNames": ["Guaricica-da-serra"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Verticilada",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Inflorescência amarela terminal exuberante.",
    "description": "Altitude."
  },
  {
    "id": "422",
    "scientificName": "Campomanesia guaviroba",
    "popularNames": ["Guavirova-de-porco"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto grande globoso ácido.",
    "description": "Mata Ciliar."
  },
  {
    "id": "423",
    "scientificName": "Inga virescens",
    "popularNames": ["Ingá-verde"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Raque alada, folhas densamente verdes.",
    "description": "Beira de rio."
  },
  {
    "id": "424",
    "scientificName": "Machaerium brasiliense",
    "popularNames": ["Jacarandá"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Vermelho",
    "spines": false,
    "specialFeatures": "Exudato vermelho ao corte.",
    "description": "Madeira nobre."
  },
  {
    "id": "425",
    "scientificName": "Guibourtia hymenaeifolia",
    "popularNames": ["Jatobá-mirim"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Par de folíolos menores que o jatobá comum.",
    "description": "Cerradão."
  },
  {
    "id": "426",
    "scientificName": "Caesalpinia ferrea",
    "popularNames": ["Jucá", "Pau-ferro"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco liso manchado descamante.",
    "description": "Ornamental e medicinal."
  },
  {
    "id": "427",
    "scientificName": "Mimosa tenuiflora",
    "popularNames": ["Jurema-preta"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Muitos acúleos, casca escura rugosa.",
    "description": "Semiárido e transição."
  },
  {
    "id": "428",
    "scientificName": "Sapium glandulatum",
    "popularNames": ["Leiteiro-da-mata"],
    "family": "Euphorbiaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Par de glândulas no pecíolo.",
    "description": "Pioneira."
  },
  {
    "id": "429",
    "scientificName": "Sclerolobium aureum",
    "popularNames": ["Pau-pombo", "Pau-bosta"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Indumento dourado nos ramos e raque.",
    "description": "Cerrado típico."
  },
  {
    "id": "430",
    "scientificName": "Ochroma pyramidale",
    "popularNames": ["Pau-de-balsa"],
    "family": "Malvaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Madeira extremamente leve.",
    "description": "Crescimento ultrarrápido."
  },
  {
    "id": "431",
    "scientificName": "Physocalymma scaberrimum",
    "popularNames": ["Pau-de-rosas"],
    "family": "Lythraceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flores rosa choque, madeira rosada.",
    "description": "Transição cerrado-mata."
  },
  {
    "id": "432",
    "scientificName": "Simarouba versicolor",
    "popularNames": ["Pau-paraíba"],
    "family": "Simaroubaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas brilhosas, casca amarga.",
    "description": "Cerrado e Mata Seca."
  },
  {
    "id": "433",
    "scientificName": "Centrolobium paraense",
    "popularNames": ["Pau-rainha"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Vermelho",
    "spines": false,
    "specialFeatures": "Fruto samara grande espinhoso.",
    "description": "Mata."
  },
  {
    "id": "434",
    "scientificName": "Aspidosperma pyrifolium",
    "popularNames": ["Pereiro"],
    "family": "Apocynaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Folhas elípticas, látex branco.",
    "description": "Mata Seca."
  },
  {
    "id": "435",
    "scientificName": "Cinnamodendron dinisii",
    "popularNames": ["Pimenteira"],
    "family": "Canellaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas com sabor picante.",
    "description": "Mata Atlântica."
  },
  {
    "id": "436",
    "scientificName": "Tibouchina sellowiana",
    "popularNames": ["Quaresmeira-serra"],
    "family": "Melastomataceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flores brancas que mudam para lilás.",
    "description": "Altitude."
  },
  {
    "id": "437",
    "scientificName": "Rhamnidium elaeocarpum",
    "popularNames": ["Saguaraji-amarelo"],
    "family": "Rhamnaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Nervuras secundárias paralelas atingem a margem.",
    "description": "Mata."
  },
  {
    "id": "438",
    "scientificName": "Erythrina speciosa",
    "popularNames": ["Suinã"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Flores vermelhas 'bico-de-papagaio', tronco espinhoso.",
    "description": "Mata úmida."
  },
  {
    "id": "439",
    "scientificName": "Bagassa guianensis",
    "popularNames": ["Tatajuba"],
    "family": "Moraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Folhas cordiformes trilobadas (jovens).",
    "description": "Mata alta."
  },
  {
    "id": "440",
    "scientificName": "Lonchocarpus nitidus",
    "popularNames": ["Timbó-miúdo"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos brilhosos, inflorescência rósea.",
    "description": "Mata Ciliar."
  },
  {
    "id": "441",
    "scientificName": "Abarema brachystachya",
    "popularNames": ["Timbuva-da-serra"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Vagens contorcidas vermelhas internamente.",
    "description": "Mata."
  },
  {
    "id": "442",
    "scientificName": "Virola sebifera",
    "popularNames": ["Ucuúba-do-cerrado"],
    "family": "Myristicaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Vermelho",
    "spines": false,
    "specialFeatures": "Exudato vermelho translúcido, folhas dísticas.",
    "description": "Mata e Cerradão."
  },
  {
    "id": "443",
    "scientificName": "Eugenia pyriformis",
    "popularNames": ["Uvaia"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Frutos amarelos aveludados muito aromáticos.",
    "description": "Mata e pomar."
  },
  {
    "id": "444",
    "scientificName": "Piptocarpha axillaris",
    "popularNames": ["Vassourão-branco"],
    "family": "Asteraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha discolor, face inferior branca.",
    "description": "Mata Seca."
  },
  {
    "id": "445",
    "scientificName": "Dalbergia cearensis",
    "popularNames": ["Violeta"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Madeira estriada cor de violeta.",
    "description": "Caatinga/Transição."
  },
  {
    "id": "446",
    "scientificName": "Parapiptadenia rigida",
    "popularNames": ["Angico-vermelho", "Gurucaia"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Madeira muito pesada, casca descamante.",
    "description": "Mata Atlântica."
  },
  {
    "id": "447",
    "scientificName": "Annona coriacea",
    "popularNames": ["Araticum-liso"],
    "family": "Annonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha coriácea glabra.",
    "description": "Cerrado típico."
  },
  {
    "id": "448",
    "scientificName": "Annona cacans",
    "popularNames": ["Araticum-cagão"],
    "family": "Annonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto baga lisa amarela.",
    "description": "Mata úmida."
  },
  {
    "id": "449",
    "scientificName": "Myroxylon peruiferum",
    "popularNames": ["Bálsamo", "Cabreuva"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Folíolos com pontuações e linhas translúcidas.",
    "description": "Madeira aromática."
  },
  {
    "id": "450",
    "scientificName": "Amburana cearensis",
    "popularNames": ["Cerejeira", "Imburana"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Casca avermelhada que se solta em finas lâminas.",
    "description": "Madeira nobre."
  },
  {
    "id": "451",
    "scientificName": "Psidium guajava",
    "popularNames": ["Goiabeira"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco liso escamoso, ramos quadrangulares.",
    "description": "Frutífera invasora."
  },
  {
    "id": "452",
    "scientificName": "Schizolobium parahyba",
    "popularNames": ["Guapuruvu"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Crescimento rapidíssimo, cicatrizes grandes no tronco.",
    "description": "Pioneira mata."
  },
  {
    "id": "453",
    "scientificName": "Pseudobombax grandiflorum",
    "popularNames": ["Imbiruçu"],
    "family": "Malvaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flores brancas grandes 'escova'.",
    "description": "Rupestre."
  },
  {
    "id": "454",
    "scientificName": "Inga edulis",
    "popularNames": ["Ingá-cipó"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Raque alada, fruto vagem longa cilíndrica.",
    "description": "Mata ciliar."
  },
  {
    "id": "455",
    "scientificName": "Tabebuia ochracea",
    "popularNames": ["Ipê-amarelo-campo"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Densa pilosidade ferrugínea nas folhas.",
    "description": "Cerrado."
  },
  {
    "id": "456",
    "scientificName": "Handroanthus heptaphyllus",
    "popularNames": ["Ipê-roxo-sete-folhas"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "7 folíolos (geralmente), flores roxas.",
    "description": "Mata."
  },
  {
    "id": "457",
    "scientificName": "Hexachlamys edulis",
    "popularNames": ["Ivaí"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas pilosas, fruto alaranjado comestível.",
    "description": "Sub-bosque."
  },
  {
    "id": "458",
    "scientificName": "Syzygium malaccense",
    "popularNames": ["Jambo-vermelho"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas grandes coriáceas, flores pink.",
    "description": "Exótica naturalizada."
  },
  {
    "id": "459",
    "scientificName": "Cariniana estrellensis",
    "popularNames": ["Jequitibá-branco"],
    "family": "Lecythidaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Árvore gigante, fruto pixídio lenhoso.",
    "description": "Mata Atlântica."
  },
  {
    "id": "460",
    "scientificName": "Cordia trichotoma",
    "popularNames": ["Louro-pardo"],
    "family": "Boraginaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Copa estratificada, flores brancas abundantes.",
    "description": "Madeira nobre."
  },
  {
    "id": "461",
    "scientificName": "Cyclolobium vecchii",
    "popularNames": ["Louveira"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas brilhantes, madeira amarela.",
    "description": "Mata."
  },
  {
    "id": "462",
    "scientificName": "Erythrina velutina",
    "popularNames": ["Mulungu"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Tronco suberoso com espinhos.",
    "description": "Transição."
  },
  {
    "id": "463",
    "scientificName": "Aegiphila sellowiana",
    "popularNames": ["Papagaio"],
    "family": "Lamiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas aveludadas, fruto amarelo.",
    "description": "Pioneira mata."
  },
  {
    "id": "464",
    "scientificName": "Bauhinia forficata",
    "popularNames": ["Pata-de-vaca-branca"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Acúleos estipulares, flor branca.",
    "description": "Mata."
  },
  {
    "id": "465",
    "scientificName": "Senna multijuga",
    "popularNames": ["Pau-cigarra"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Paripinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Muitos folíolos pequenos, flor amarela.",
    "description": "Pioneira mata."
  },
  {
    "id": "466",
    "scientificName": "Triplaris americana",
    "popularNames": ["Pau-formiga"],
    "family": "Polygonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco oco habitado por formigas ferozes.",
    "description": "Mata Ciliar."
  },
  {
    "id": "467",
    "scientificName": "Eugenia uniflora",
    "popularNames": ["Pitangueira"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas brilhantes aromáticas, fruto sulcado.",
    "description": "Mata e pomar."
  },
  {
    "id": "468",
    "scientificName": "Rapanea guianensis",
    "popularNames": ["Pororoca"],
    "family": "Primulaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Pontuações negras nas folhas, frutos sésseis.",
    "description": "Mata úmida."
  },
  {
    "id": "469",
    "scientificName": "Sapindus saponaria",
    "popularNames": ["Saboeiro"],
    "family": "Sapindaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Raque alada, fruto faz espuma na água.",
    "description": "Mata."
  },
  {
    "id": "470",
    "scientificName": "Colubrina glandulosa",
    "popularNames": ["Saguaragi"],
    "family": "Rhamnaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Glândulas na base da lâmina foliar.",
    "description": "Madeira nobre."
  },
  {
    "id": "471",
    "scientificName": "Caesalpinia pluviosa",
    "popularNames": ["Sibipiruna"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor amarela, vagem achatada lenhosa.",
    "description": "Ornamental clássica."
  },
  {
    "id": "472",
    "scientificName": "Vitex montevidensis",
    "popularNames": ["Tarumã"],
    "family": "Lamiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto preto consumido por aves e peixes.",
    "description": "Mata úmida."
  },
  {
    "id": "473",
    "scientificName": "Carpotroche brasiliensis",
    "popularNames": ["Sapucainha"],
    "family": "Achariaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto grande alado irregular.",
    "description": "Sub-bosque."
  },
  {
    "id": "474",
    "scientificName": "Astronium graveolens",
    "popularNames": ["Guaritá"],
    "family": "Anacardiaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Serreada",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Folhas aromáticas, madeira tigrada.",
    "description": "Madeira de lei."
  },
  {
    "id": "475",
    "scientificName": "Annona rugulosa",
    "popularNames": ["Araticum-de-porco"],
    "family": "Annonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas rugosas, fruto comestível.",
    "description": "Mata."
  },
  {
    "id": "476",
    "scientificName": "Mimosa pilulifera",
    "popularNames": ["Bracatinga-do-banhado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Copa globosa densa.",
    "description": "Zonas úmidas."
  },
  {
    "id": "477",
    "scientificName": "Symplocos glanduloso-marginata",
    "popularNames": ["Bracunhá"],
    "family": "Symplocaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Crenada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Glândulas negras na margem da folha.",
    "description": "Altitude."
  },
  {
    "id": "478",
    "scientificName": "Butia eriospatha",
    "popularNames": ["Butiá-da-serra"],
    "family": "Arecaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Folhas azuladas, espata lanosa.",
    "description": "Serra."
  },
  {
    "id": "479",
    "scientificName": "Cinnamomum sellowianum",
    "popularNames": ["Canela-raposa"],
    "family": "Lauraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha discolor, cheiro de canela.",
    "description": "Mata."
  },
  {
    "id": "480",
    "scientificName": "Pachira glabra",
    "popularNames": ["Castanha-da-praia"],
    "family": "Malvaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco verde, flores brancas grandes.",
    "description": "Úmida e ornamental."
  },
  {
    "id": "481",
    "scientificName": "Poincianella pyramidalis",
    "popularNames": ["Catingueira"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos orbiculares.",
    "description": "Caatinga."
  },
  {
    "id": "482",
    "scientificName": "Styrax acuminatus",
    "popularNames": ["Caujujão"],
    "family": "Styracaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas acuminadas, face inferior branca.",
    "description": "Mata."
  },
  {
    "id": "483",
    "scientificName": "Solanum bullatum",
    "popularNames": ["Fumo-bravo"],
    "family": "Solanaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas rugosas buladas.",
    "description": "Pioneira."
  },
  {
    "id": "484",
    "scientificName": "Parkia platycephala",
    "popularNames": ["Faveira"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flores em capítulos globosos.",
    "description": "Mata e Cerrado."
  },
  {
    "id": "485",
    "scientificName": "Dasyphyllum tomentosum",
    "popularNames": ["Guaiapá"],
    "family": "Asteraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Espinhos bifurcados, folha tomentosa.",
    "description": "Cerradão."
  },
  {
    "id": "486",
    "scientificName": "Campomanesia rhombea",
    "popularNames": ["Guaviroveira-folha-crespa"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas com margens onduladas/crespas.",
    "description": "Mata Atlântica."
  },
  {
    "id": "487",
    "scientificName": "Cecropia sciadophylla",
    "popularNames": ["Imbaúba-do-norte"],
    "family": "Urticaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas profundamente lobadas.",
    "description": "Mata alta."
  },
  {
    "id": "488",
    "scientificName": "Machaerium paraguariense",
    "popularNames": ["Jacarandá-cipó"],
    "family": "Fabaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Vermelho",
    "spines": false,
    "specialFeatures": "Hábito trepador, seiva vermelha.",
    "description": "Mata."
  },
  {
    "id": "489",
    "scientificName": "Dalbergia miscolobium",
    "popularNames": ["Jacarandá-do-cerrado-falso"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos azulados.",
    "description": "Cerrado."
  },
  {
    "id": "490",
    "scientificName": "Platymiscium floribundum",
    "popularNames": ["Jacarandá-do-litoral"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas opostas (raro em Fabaceae).",
    "description": "Mata Atlântica."
  },
  {
    "id": "491",
    "scientificName": "Oreopanax fulvus",
    "popularNames": ["Mamona-do-mato"],
    "family": "Araliaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Indumento ferrugíneo denso.",
    "description": "Mata de altitude."
  },
  {
    "id": "492",
    "scientificName": "Geoffroea spinosa",
    "popularNames": ["Marizeiro"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Ramos terminam em espinhos.",
    "description": "Mata ciliar."
  },
  {
    "id": "493",
    "scientificName": "Lafoensia glyptocarpa",
    "popularNames": ["Merindiba-rosa"],
    "family": "Lythraceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco liso claro, flores brancas.",
    "description": "Mata Atlântica."
  },
  {
    "id": "494",
    "scientificName": "Eugenia multicostata",
    "popularNames": ["Pau-alazão"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco avermelhado liso.",
    "description": "Mata alta."
  },
  {
    "id": "495",
    "scientificName": "Cordia glazioviana",
    "popularNames": ["Pau-branco-louro"],
    "family": "Boraginaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flores brancas em cachos.",
    "description": "Transição."
  },
  {
    "id": "496",
    "scientificName": "Guateria villosissima",
    "popularNames": ["Pindaíba-preta"],
    "family": "Annonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Muitos pelos (vilosidades) nos ramos.",
    "description": "Sub-bosque."
  },
  {
    "id": "497",
    "scientificName": "Ocotea fasciculata",
    "popularNames": ["Canela-fogo"],
    "family": "Lauraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Odor aromático picante.",
    "description": "Mata Atlântica."
  },
  {
    "id": "498",
    "scientificName": "Pera glabrata",
    "popularNames": ["Tamanqueiro"],
    "family": "Peraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas rígidas verde-limão.",
    "description": "Pioneira."
  },
  {
    "id": "499",
    "scientificName": "Huberia ovalifolia",
    "popularNames": ["Hubéria"],
    "family": "Melastomataceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Nervuras curvinérveas, flores brancas.",
    "description": "Altitude."
  },
  {
    "id": "500",
    "scientificName": "Zanthoxylum pohlianum",
    "popularNames": ["Mamica-de-cadela"],
    "family": "Rutaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Crenada",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Tronco com acúleos curtos e grossos.",
    "description": "Madeira de lei."
  }
];