// db_part2.js - Espécies 201 a 400
export const speciesDataPart2 = [
  {
    "id": "201",
    "scientificName": "Palicourea marcgravii",
    "popularNames": ["Erva-de-rato"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Extremamente tóxica (mata gado). Folhas opostas cruzadas.",
    "description": "Perigosa para rebanhos."
  },
  {
    "id": "202",
    "scientificName": "Psychotria hoffmannseggiana",
    "popularNames": ["Erva-de-rato-de-bode"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Inflorescência envolvida por brácteas coloridas (roxas/vermelhas).",
    "description": "Sub-bosque."
  },
  {
    "id": "203",
    "scientificName": "Psychotria carthagenensis",
    "popularNames": ["Erva-de-gralha"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Estípulas grandes que caem e deixam cicatriz anelar.",
    "description": "Frutos laranja/vermelhos."
  },
  {
    "id": "204",
    "scientificName": "Chomelia pohliana",
    "popularNames": ["Espinho-de-agulha"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Espinhos longos e finos (agulha) nas axilas. Ramos horizontais.",
    "description": "Mata seca."
  },
  {
    "id": "205",
    "scientificName": "Cordiera edulis",
    "popularNames": ["Marmelada-nativa"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto preto globoso comestível. Folha lustrosa.",
    "description": "Dioica."
  },
  {
    "id": "206",
    "scientificName": "Bathysa australis",
    "popularNames": ["Macuqueiro"],
    "family": "Rubiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas grandes com estípula terminal grande (bico).",
    "description": "Mata úmida/ciliar."
  },
  {
    "id": "207",
    "scientificName": "Miconia fallax",
    "popularNames": ["Veludo"],
    "family": "Melastomataceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Denticulada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Face superior verde escuro, inferior branco tomentoso (bicolor).",
    "description": "Cerrado."
  },
  {
    "id": "208",
    "scientificName": "Miconia chamissois",
    "popularNames": ["Pixirica"],
    "family": "Melastomataceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Glabra (sem pelos). Nervuras impressedas.",
    "description": "Fruto roxo comestível por aves."
  },
  {
    "id": "209",
    "scientificName": "Miconia stenostachya",
    "popularNames": ["Miconia-prateada"],
    "family": "Melastomataceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas estreitas, face inferior prateada.",
    "description": "Cerrado ralo."
  },
  {
    "id": "210",
    "scientificName": "Tibouchina candolleana",
    "popularNames": ["Quaresmeira"],
    "family": "Melastomataceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flores roxas com centro branco. Folhas aveludadas.",
    "description": "Ornamental."
  },
  {
    "id": "211",
    "scientificName": "Pleroma granulosum",
    "popularNames": ["Quaresmeira-roxa"],
    "family": "Melastomataceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Antiga Tibouchina granulosa. Flores roxas escuras.",
    "description": "Mata Atlântica/Transição."
  },
  {
    "id": "212",
    "scientificName": "Lavoisiera imbricata",
    "popularNames": ["Lavoisiera"],
    "family": "Melastomataceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas minúsculas imbricadas (escamas) coladas no caule.",
    "description": "Campo rupestre/Cerrado altitude."
  },
  {
    "id": "213",
    "scientificName": "Microlicia humilis",
    "popularNames": ["Microlicia"],
    "family": "Melastomataceae",
    "type": "Subarbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor rosa/lilás com estames amarelos dimórficos.",
    "description": "Campo limpo."
  },
  {
    "id": "214",
    "scientificName": "Trembleya phlogiformis",
    "popularNames": ["Trembleya"],
    "family": "Melastomataceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flores brancas e rosas na mesma planta (mudam com a idade).",
    "description": "Campo rupestre."
  },
  {
    "id": "215",
    "scientificName": "Strychnos parvifolia",
    "popularNames": ["Capitao-zinho"],
    "family": "Loganiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Espinhos axilares pequenos. Folhas redondas pequenas.",
    "description": "Cerrado."
  },
  {
    "id": "216",
    "scientificName": "Baccharis dracunculifolia",
    "popularNames": ["Alecrim-do-campo"],
    "family": "Asteraceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Cheiro característico de própolis. Folhas lineares.",
    "description": "Fonte de própolis verde."
  },
  {
    "id": "217",
    "scientificName": "Baccharis trimera",
    "popularNames": ["Carqueja"],
    "family": "Asteraceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Ausente",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Caule alado (três asas). Folhas reduzidas/ausentes.",
    "description": "Medicinal."
  },
  {
    "id": "218",
    "scientificName": "Chromolaena laevigata",
    "popularNames": ["Mata-pasto"],
    "family": "Asteraceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Inflorescência lilás claro. Folha áspera.",
    "description": "Invasora de pasto."
  },
  {
    "id": "219",
    "scientificName": "Copaifera oblongifolia",
    "popularNames": ["Pau-d'óleo-miúdo"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Arbusto baixo. Folíolos coriáceos retangulares.",
    "description": "Cerrado ralo."
  },
  {
    "id": "220",
    "scientificName": "Mimosa claussenii",
    "popularNames": ["Mimosa-de-espinho"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Muitos acúleos recurvos. Folíolos sensitivos.",
    "description": "Cerrado."
  },
  {
    "id": "221",
    "scientificName": "Calliandra brevipes",
    "popularNames": ["Esponjinha"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos finos juntos. Flores rosa/branco.",
    "description": "Beira de rio/ornamental."
  },
  {
    "id": "222",
    "scientificName": "Bauhinia cupulata",
    "popularNames": ["Bauínia"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha bilobada grande. Cálice floral longo.",
    "description": "Mata."
  },
  {
    "id": "223",
    "scientificName": "Senna rugosa",
    "popularNames": ["Fedegoso"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Paripinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas rugosas. Flores amarelas assimétricas.",
    "description": "Invasora de pasto."
  },
  {
    "id": "224",
    "scientificName": "Senna silvestris",
    "popularNames": ["Fedegoso-do-mato"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Paripinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas lisas. Vagem longa plana.",
    "description": "Mata ciliar/cerradão."
  },
  {
    "id": "225",
    "scientificName": "Senna occidentalis",
    "popularNames": ["Fedegoso-café"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Paripinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Cheiro ruim nas folhas. Sementes usadas como café falso.",
    "description": "Ruderal."
  },
  {
    "id": "226",
    "scientificName": "Lantana camara",
    "popularNames": ["Cambará"],
    "family": "Verbenaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Ramos quadrangulares com acúleos. Flores multicoloridas.",
    "description": "Ornamental/Invasora."
  },
  {
    "id": "227",
    "scientificName": "Stachytarpheta cayennensis",
    "popularNames": ["Gervão"],
    "family": "Verbenaceae",
    "type": "Subarbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Inflorescência espiga longa fina. Flores azuis/roxas.",
    "description": "Medicinal."
  },
  {
    "id": "228",
    "scientificName": "Lippia alba",
    "popularNames": ["Erva-cidreira-de-arbusto"],
    "family": "Verbenaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Cheiro forte de limão/cidreira ao esmagar.",
    "description": "Medicinal calmante."
  },
  {
    "id": "229",
    "scientificName": "Aloysia virgata",
    "popularNames": ["Lixa-branca"],
    "family": "Verbenaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha muito áspera. Inflorescência branca racemosa.",
    "description": "Mata."
  },
  {
    "id": "230",
    "scientificName": "Duranta erecta",
    "popularNames": ["Violeteira"],
    "family": "Verbenaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Frutos amarelos em cacho (tóxicos). Espinhos axilares.",
    "description": "Ornamental."
  },
  {
    "id": "231",
    "scientificName": "Pyrostegia venusta",
    "popularNames": ["Cipó-de-são-joão"],
    "family": "Bignoniaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Gavinha trifída na ponta. Flores laranjas tubulares.",
    "description": "Muito vistosa no inverno."
  },
  {
    "id": "232",
    "scientificName": "Arrabidaea chica",
    "popularNames": ["Pariri", "Crajiru"],
    "family": "Bignoniaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas ficam vermelho-cobre quando secas.",
    "description": "Medicinal."
  },
  {
    "id": "233",
    "scientificName": "Amphilophium crucigerum",
    "popularNames": ["Pente-de-macaco"],
    "family": "Bignoniaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto cápsula espinhosa/rugosa larga.",
    "description": "Mata."
  },
  {
    "id": "234",
    "scientificName": "Dolichandra unguis-cati",
    "popularNames": ["Unha-de-gato"],
    "family": "Bignoniaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Gavinha terminando em três garras (unha de gato).",
    "description": "Mata."
  },
  {
    "id": "235",
    "scientificName": "Memora peregrina",
    "popularNames": ["Cipó-de-tucano"],
    "family": "Bignoniaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Arbusto escandente. Folíolos coriáceos.",
    "description": "Cerrado."
  },
  {
    "id": "236",
    "scientificName": "Celtis pubescens",
    "popularNames": ["Juá-mirim"],
    "family": "Cannabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Base da folha assimétrica trinervada. Áspera.",
    "description": "Fruto amarelo comestível."
  },
  {
    "id": "237",
    "scientificName": "Solanum crinitum",
    "popularNames": ["Jurubebão"],
    "family": "Solanaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Fruto gigante (tamanho melão). Folhas enormes.",
    "description": "Invasora."
  },
  {
    "id": "238",
    "scientificName": "Solanum viarum",
    "popularNames": ["Joá-bravo"],
    "family": "Solanaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Fruto rajado verde/branco. Muito espinho.",
    "description": "Tóxica."
  },
  {
    "id": "239",
    "scientificName": "Cestrum strigillatum",
    "popularNames": ["Coama"],
    "family": "Solanaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Cheiro foetido nas folhas (marianeira).",
    "description": "Mata ciliar."
  },
  {
    "id": "240",
    "scientificName": "Acnistus arborescens",
    "popularNames": ["Fruta-de-sabiá"],
    "family": "Solanaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Muitos frutos pequenos laranjas no caule.",
    "description": "Atrai muitos pássaros."
  },
  {
    "id": "241",
    "scientificName": "Piper arboreum",
    "popularNames": ["Fruto-de-morcego"],
    "family": "Piperaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Base da folha assimétrica (um lado maior).",
    "description": "Mata úmida."
  },
  {
    "id": "242",
    "scientificName": "Piper amalago",
    "popularNames": ["Jaborandi-manso"],
    "family": "Piperaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Cheiro de anis/erva-doce.",
    "description": "Mata."
  },
  {
    "id": "243",
    "scientificName": "Manihot caerulescens",
    "popularNames": ["Mandioca-brava-do-cerrado"],
    "family": "Euphorbiaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Folha de mandioca. Látex abundante. Tóxica.",
    "description": "Cerrado."
  },
  {
    "id": "244",
    "scientificName": "Cnidoscolus phyllacanthus",
    "popularNames": ["Favela"],
    "family": "Euphorbiaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Branco (Látex)",
    "spines": true,
    "specialFeatures": "Pelos urticantes (queimam). Estrutura espinhosa.",
    "description": "Caatinga/Transição."
  },
  {
    "id": "245",
    "scientificName": "Jatropha curcas",
    "popularNames": ["Pinhão-manso"],
    "family": "Euphorbiaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Folha cordiforme lobada. Látex branco.",
    "description": "Biodiesel."
  },
  {
    "id": "246",
    "scientificName": "Ricinus communis",
    "popularNames": ["Mamona"],
    "family": "Euphorbiaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha peltada palmada. Fruto com espinhos moles.",
    "description": "Invasora comum."
  },
  {
    "id": "247",
    "scientificName": "Hedyosmum brasiliense",
    "popularNames": ["Chá-de-bugre"],
    "family": "Chloranthaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Bainha estipular envolve o nó. Cheiro de limão.",
    "description": "Mata úmida."
  },
  {
    "id": "248",
    "scientificName": "Drimys brasiliensis",
    "popularNames": ["Cataia", "Casca-de-anta"],
    "family": "Winteraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Casca e folha picante. Face inferior branca.",
    "description": "Mata de galeria altitude."
  },
  {
    "id": "249",
    "scientificName": "Mollinedia widgrenii",
    "popularNames": ["Pimenteira"],
    "family": "Monimiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Dentada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Dentes da margem espaçados. Cheiro aromático.",
    "description": "Sub-bosque."
  },
  {
    "id": "250",
    "scientificName": "Siparuna apiosyce",
    "popularNames": ["Limão-bravo"],
    "family": "Siparunaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Pubescência estrelada. Cheiro cítrico forte.",
    "description": "Mata."
  },
  {
    "id": "251",
    "scientificName": "Myrsine umbellata",
    "popularNames": ["Capororoca"],
    "family": "Primulaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Pecíolo avermelhado decurrente.",
    "description": "Mata."
  },
  {
    "id": "252",
    "scientificName": "Stylosanthes guianensis",
    "popularNames": ["Meladinha"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Viscosa (pegajosa). Flores amarelas pequenas.",
    "description": "Forrageira."
  },
  {
    "id": "253",
    "scientificName": "Crotalaria maypurensis",
    "popularNames": ["Chocalho"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Vagem inflada (faz barulho quando seca).",
    "description": "Ruderal."
  },
  {
    "id": "254",
    "scientificName": "Crotalaria spectabilis",
    "popularNames": ["Chocalho-gigante"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas simples obovadas grandes. Flor amarela.",
    "description": "Adubo verde."
  },
  {
    "id": "255",
    "scientificName": "Indigofera suffruticosa",
    "popularNames": ["Anil"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Frutinhos curvos em cacho (foice).",
    "description": "Corante azul."
  },
  {
    "id": "256",
    "scientificName": "Tephrosia cinerea",
    "popularNames": ["Anil-bravo"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos cinzentos/prateados seríceos.",
    "description": "Tóxica peixes."
  },
  {
    "id": "257",
    "scientificName": "Aeschynomene paniculata",
    "popularNames": ["Angiquinho"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos pequenos sensitivos. Fruto articulado.",
    "description": "Campo."
  },
  {
    "id": "258",
    "scientificName": "Centrosema brasilianum",
    "popularNames": ["Feijão-de-ovelha"],
    "family": "Fabaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor grande roxa invertida.",
    "description": "Trepadeira herbácea."
  },
  {
    "id": "259",
    "scientificName": "Macroptilium atropurpureum",
    "popularNames": ["Siratro"],
    "family": "Fabaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos lobados (orelha). Flor roxo-escuro.",
    "description": "Forrageira."
  },
  {
    "id": "260",
    "scientificName": "Desmodium incanum",
    "popularNames": ["Pega-pega"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto lomento que gruda na roupa.",
    "description": "Gramados."
  },
  {
    "id": "261",
    "scientificName": "Piptadenia gonoacantha",
    "popularNames": ["Pau-jacaré"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Tronco com cristas longitudinais espinhosas.",
    "description": "Mata Atlântica/Transição."
  },
  {
    "id": "262",
    "scientificName": "Schinus terebinthifolia",
    "popularNames": ["Aroeira-pimenteira"],
    "family": "Anacardiaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Frutinhos vermelhos (pimenta rosa). Cheiro de manga.",
    "description": "Condimento."
  },
  {
    "id": "263",
    "scientificName": "Schinus molle",
    "popularNames": ["Aroeira-salsa"],
    "family": "Anacardiaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Ramos pendentes (chorão). Folíolos lineares.",
    "description": "Ornamental."
  },
  {
    "id": "264",
    "scientificName": "Mangifera indica",
    "popularNames": ["Manga"],
    "family": "Anacardiaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Resina cheiro de terebintina. Folhas lanceoladas.",
    "description": "Exótica naturalizada."
  },
  {
    "id": "265",
    "scientificName": "Persea americana",
    "popularNames": ["Abacate"],
    "family": "Lauraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha cheiro anisado (algumas vars).",
    "description": "Exótica cultivada."
  },
  {
    "id": "266",
    "scientificName": "Coffea arabica",
    "popularNames": ["Café"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Ondulada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Domácias nas axilas. Folha brilhante.",
    "description": "Cultivada/Sub-bosque escapada."
  },
  {
    "id": "267",
    "scientificName": "Eucalyptus sp.",
    "popularNames": ["Eucalipto"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Cheiro de eucalipto. Casca descamante.",
    "description": "Plantio exótico."
  },
  {
    "id": "268",
    "scientificName": "Pinus sp.",
    "popularNames": ["Pinus"],
    "family": "Pinaceae",
    "type": "Árvore",
    "leafArrangement": "Fasciculada",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Folhas em agulha (acículas).",
    "description": "Plantio exótico."
  },
  {
    "id": "269",
    "scientificName": "Melia azedarach",
    "popularNames": ["Cinamomo"],
    "family": "Meliaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto globoso amarelo persistente.",
    "description": "Exótica invasora."
  },
  {
    "id": "270",
    "scientificName": "Tecoma stans",
    "popularNames": ["Ipê-de-jardim"],
    "family": "Bignoniaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flores amarelas tubulares. Folíolos serreados.",
    "description": "Exótica invasora."
  },
  {
    "id": "271",
    "scientificName": "Leucaena leucocephala",
    "popularNames": ["Leucena"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Vagens planas marrons em cachos.",
    "description": "Exótica."
  },
  {
    "id": "272",
    "scientificName": "Ricinus communis",
    "popularNames": ["Mamona"],
    "family": "Euphorbiaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha peltada palmada.",
    "description": "Naturalizada."
  },
  {
    "id": "273",
    "scientificName": "Bambusa vulgaris",
    "popularNames": ["Bambu"],
    "family": "Poaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Colmo lenhoso segmentado. Folhas com bainha.",
    "description": "Touceira gigante."
  },
  {
    "id": "274",
    "scientificName": "Urochloa brizantha",
    "popularNames": ["Braquiária"],
    "family": "Poaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Capim cespitoso alto (até 1.5m).",
    "description": "Invasora gramínea."
  },
  {
    "id": "275",
    "scientificName": "Melinis minutiflora",
    "popularNames": ["Capim-gordura"],
    "family": "Poaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Folhas pegajosas com cheiro de melaço.",
    "description": "Invasora comum."
  },
  {
    "id": "276",
    "scientificName": "Vernonia polysphaera",
    "popularNames": ["Assa-peixe-branco"],
    "family": "Asteraceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Face inferior branca/tomentosa. Inflorescência ampla.",
    "description": "Melífero."
  },
  {
    "id": "277",
    "scientificName": "Moquiniastrum polymorphum",
    "popularNames": ["Cambará"],
    "family": "Asteraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha discolor, tronco tortuoso.",
    "description": "Mata."
  },
  {
    "id": "278",
    "scientificName": "Vernonanthura ferruginea",
    "popularNames": ["Assa-peixe-ferrugem"],
    "family": "Asteraceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Face inferior ferruginea. Áspera.",
    "description": "Cerrado."
  },
  {
    "id": "279",
    "scientificName": "Heteropterys byrsonimifolia",
    "popularNames": ["Murici-de-asa"],
    "family": "Malpighiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto sâmara vermelha. Folha parece murici.",
    "description": "Cerrado."
  },
  {
    "id": "280",
    "scientificName": "Banisteriopsis oxyclada",
    "popularNames": ["Cipó-prata-miúdo"],
    "family": "Malpighiaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Pêlos brancos cobrem a planta toda.",
    "description": "Trepadeira."
  },
  {
    "id": "281",
    "scientificName": "Tetrapterys ramiflora",
    "popularNames": ["Tetrápteris"],
    "family": "Malpighiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto com 4 asas em cruz (X).",
    "description": "Mata."
  },
  {
    "id": "282",
    "scientificName": "Cuspidaria sceptrum",
    "popularNames": ["Cuspidária"],
    "family": "Bignoniaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto muito longo e fino (verga).",
    "description": "Mata."
  },
  {
    "id": "283",
    "scientificName": "Fridericia chica",
    "popularNames": ["Carajuru"],
    "family": "Bignoniaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha seca fica vermelha.",
    "description": "Medicinal."
  },
  {
    "id": "284",
    "scientificName": "Tanaecium pyramidatum",
    "popularNames": ["Cipó-ó"],
    "family": "Bignoniaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas cheiram a amêndoa amarga. Fruto grosso.",
    "description": "Mata ciliar."
  },
  {
    "id": "285",
    "scientificName": "Adenocalymma peregrinum",
    "popularNames": ["Cipó-alho"],
    "family": "Bignoniaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Cheiro forte de alho na folha. Gavinha simples.",
    "description": "Mata."
  },
  {
    "id": "286",
    "scientificName": "Smilax rufescens",
    "popularNames": ["Japecanga-mansa"],
    "family": "Smilacaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Sem espinhos (diferente da S. brasiliensis).",
    "description": "Mata."
  },
  {
    "id": "287",
    "scientificName": "Dioscorea trifida",
    "popularNames": ["Cará"],
    "family": "Dioscoreaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha cordiforme (coração) ou lobada.",
    "description": "Tubérculo comestível."
  },
  {
    "id": "288",
    "scientificName": "Passiflora edulis",
    "popularNames": ["Maracujá-azedo"],
    "family": "Passifloraceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha trilobada serrilhada. Gavinhas.",
    "description": "Fruto comercial."
  },
  {
    "id": "289",
    "scientificName": "Passiflora cincinnata",
    "popularNames": ["Maracujá-do-mato"],
    "family": "Passifloraceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha pentalobada (5 lobos). Flor roxa.",
    "description": "Nativo."
  },
  {
    "id": "290",
    "scientificName": "Passiflora alata",
    "popularNames": ["Maracujá-doce"],
    "family": "Passifloraceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Caule quadrangular (alado). Folha inteira oval.",
    "description": "Fruto doce."
  },
  {
    "id": "291",
    "scientificName": "Aristolochia esperanzae",
    "popularNames": ["Papo-de-peru"],
    "family": "Aristolochiaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor em forma de papo (jarro). Folha cordiforme.",
    "description": "Tóxica."
  },
  {
    "id": "292",
    "scientificName": "Serjania lethalis",
    "popularNames": ["Cipó-timbó-de-leite"],
    "family": "Sapindaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Biternada",
    "leafMargin": "Serreada",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Látex branco abundante. Caule triangular.",
    "description": "Tóxica."
  },
  {
    "id": "293",
    "scientificName": "Paullinia cupana",
    "popularNames": ["Guaraná"],
    "family": "Sapindaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "5 folíolos. Fruto vermelho com semente preta.",
    "description": "Amazônico/Cultivado."
  },
  {
    "id": "294",
    "scientificName": "Cardiospermum halicacabum",
    "popularNames": ["Saco-de-padre"],
    "family": "Sapindaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Biternada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto balão inflado papiráceo.",
    "description": "Ruderal."
  },
  {
    "id": "295",
    "scientificName": "Urvillea ulmacea",
    "popularNames": ["Cipó-timbó"],
    "family": "Sapindaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto com 3 asas tipo samara.",
    "description": "Mata."
  },
  {
    "id": "296",
    "scientificName": "Abutilon megapotamicum",
    "popularNames": ["Lanterna-chinesa"],
    "family": "Malvaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor pendente vermelha e amarela.",
    "description": "Ornamental."
  },
  {
    "id": "297",
    "scientificName": "Sida rhombifolia",
    "popularNames": ["Guanxuma"],
    "family": "Malvaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha losangular. Fibrosa.",
    "description": "Ruderal."
  },
  {
    "id": "298",
    "scientificName": "Urena lobata",
    "popularNames": ["Guaxima"],
    "family": "Malvaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto com ganchos (carrapicho). Flores rosas.",
    "description": "Fibrosa."
  },
  {
    "id": "299",
    "scientificName": "Pavonia sepium",
    "popularNames": ["Pavonia"],
    "family": "Malvaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Estípulas lineares persistentes.",
    "description": "Sombra."
  },
  {
    "id": "300",
    "scientificName": "Hibiscus rosa-sinensis",
    "popularNames": ["Hibisco"],
    "family": "Malvaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor grande vistosa com coluna estaminal longa.",
    "description": "Exótica."
  },
  {
    "id": "301",
    "scientificName": "Chamaecrista flexuosa",
    "popularNames": ["Jureminha-do-campo"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Paripinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas sensitivas com folíolos pequenos.",
    "description": "Cerrado ralo."
  },
  {
    "id": "302",
    "scientificName": "Chamaecrista orbiculata",
    "popularNames": ["Moeda"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos redondos grandes (moedas). Viscosa.",
    "description": "Campo rupestre."
  },
  {
    "id": "303",
    "scientificName": "Mimosa nuda",
    "popularNames": ["Sensitiva"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "specialFeatures": "Apenas uma flor rosa por glomérulo.",
    "description": "Gramados e campos."
  },
  {
    "id": "304",
    "scientificName": "Andira humilis",
    "popularNames": ["Angelim-rasteiro"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Xilopódio subterrâneo enorme. Planta baixa.",
    "description": "Fruto drupa marrom."
  },
  {
    "id": "305",
    "scientificName": "Campomanesia adamantium",
    "popularNames": ["Gabiroba-verde"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas rígidas, cheiro de goiaba.",
    "description": "Cerrado."
  },
  {
    "id": "306",
    "scientificName": "Campomanesia pubescens",
    "popularNames": ["Gabiroba-peluda"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Ondulada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas hirsutas (peludas), onduladas.",
    "description": "Fruto doce."
  },
  {
    "id": "307",
    "scientificName": "Eugenia punicifolia",
    "popularNames": ["Cerejinha-do-cerrado"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto vermelho pequeno globoso.",
    "description": "Campo sujo."
  },
  {
    "id": "308",
    "scientificName": "Eugenia dysenterica",
    "popularNames": ["Cagaita"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto amarelo pálido achatado. Casca descamante.",
    "description": "Fruto laxante se quente."
  },
  {
    "id": "309",
    "scientificName": "Psidium cattleyanum",
    "popularNames": ["Araçá-vermelho"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas obovadas lisas. Fruto vermelho.",
    "description": "Comum."
  },
  {
    "id": "310",
    "scientificName": "Psidium myrtoides",
    "popularNames": ["Araçá-roxo"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto roxo escuro. Folhas lanceoladas.",
    "description": "Mata."
  },
  {
    "id": "311",
    "scientificName": "Myrcia tomentosa",
    "popularNames": ["Goiabinha-do-campo"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas aveludadas (tomentosas).",
    "description": "Cerrado."
  },
  {
    "id": "312",
    "scientificName": "Myrcia splendens",
    "popularNames": ["Mirtilo-brasileiro"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas brilhantes. Fruto preto comestível.",
    "description": "Mata."
  },
  {
    "id": "313",
    "scientificName": "Blepharocalyx salicifolius",
    "popularNames": ["Murta"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Casca lisa descamante. Cheiro de eugenol.",
    "description": "Mata ciliar."
  },
  {
    "id": "314",
    "scientificName": "Aspidosperma tomentosum",
    "popularNames": ["Peroba-do-campo"],
    "family": "Apocynaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Folhas concentradas na ponta. Fruto 'boca de sapo'.",
    "description": "Cerrado corrugado."
  },
  {
    "id": "315",
    "scientificName": "Aspidosperma macrocarpon",
    "popularNames": ["Guatambu-grande"],
    "family": "Apocynaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Frutos enormes (parece arraia).",
    "description": "Cerradão."
  },
  {
    "id": "316",
    "scientificName": "Hancornia speciosa",
    "popularNames": ["Mangaba"],
    "family": "Apocynaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Látex branco abundante. Fruto manchado.",
    "description": "Clássica do cerrado."
  },
  {
    "id": "317",
    "scientificName": "Himatanthus obovatus",
    "popularNames": ["Vigora"],
    "family": "Apocynaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Folhas obovadas agrupadas no ápice.",
    "description": "Cerrado."
  },
  {
    "id": "318",
    "scientificName": "Mandevilla velutina",
    "popularNames": ["Jalapa-do-campo"],
    "family": "Apocynaceae",
    "type": "Subarbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Flores rosas grandes com tubo longo.",
    "description": "Mata."
  },
  {
    "id": "319",
    "scientificName": "Macrosiphonia velame",
    "popularNames": ["Velame-branco"],
    "family": "Apocynaceae",
    "type": "Subarbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Planta toda branca lanosa. Flor branca.",
    "description": "Campo limpo."
  },
  {
    "id": "320",
    "scientificName": "Erythroxylum suberosum",
    "popularNames": ["Mercurio-do-campo"],
    "family": "Erythroxylaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Cortiça grossa no caule. 'Linhas' paralelas à nervura.",
    "description": "Tronco 'cascudo'."
  },
  {
    "id": "321",
    "scientificName": "Erythroxylum tortuosum",
    "popularNames": ["Azedinha"],
    "family": "Erythroxylaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Ramos muito tortuosos escuros. Estípulas triangulares.",
    "description": "Cerrado."
  },
  {
    "id": "322",
    "scientificName": "Erythroxylum campestre",
    "popularNames": ["Cabelo-de-negro"],
    "family": "Erythroxylaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Subarbusto baixo ramificado desde a base.",
    "description": "Campo cerrado."
  },
  {
    "id": "323",
    "scientificName": "Erythroxylum daphnites",
    "popularNames": ["Coca-do-cerrado"],
    "family": "Erythroxylaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas elípticas, estípulas persistentes.",
    "description": "Mata."
  },
  {
    "id": "324",
    "scientificName": "Vellozia squamata",
    "popularNames": ["Canela-de-ema"],
    "family": "Velloziaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serrilhada",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Caudice coberto por bases foliares velhas.",
    "description": "Símbolo rupestre."
  },
  {
    "id": "325",
    "scientificName": "Vellozia flavicans",
    "popularNames": ["Canela-de-ema-gigante"],
    "family": "Velloziaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serrilhada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Grande porte (até 4m). Tronco grosso.",
    "description": "Serra."
  },
  {
    "id": "326",
    "scientificName": "Kielmeyera coriacea",
    "popularNames": ["Pau-santo"],
    "family": "Calophyllaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Látex branco escasso. Folha glauca.",
    "description": "Comum."
  },
  {
    "id": "327",
    "scientificName": "Kielmeyera speciosa",
    "popularNames": ["Pau-santo-da-serra"],
    "family": "Calophyllaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Folhas aglomeradas no ápice. Nervura marginal.",
    "description": "Rupestre."
  },
  {
    "id": "328",
    "scientificName": "Kielmeyera rubriflora",
    "popularNames": ["Rosa-do-campo"],
    "family": "Calophyllaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Flores rosa. Folhas sésseis.",
    "description": "Campo."
  },
  {
    "id": "329",
    "scientificName": "Calophyllum brasiliense",
    "popularNames": ["Guanandi"],
    "family": "Calophyllaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Amarelo (Látex)",
    "spines": false,
    "specialFeatures": "Látex amarelo. Nervuras finas e paralelas.",
    "description": "Mata brejosa."
  },
  {
    "id": "330",
    "scientificName": "Mahurea palustris",
    "popularNames": ["Mureru"],
    "family": "Calophyllaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Sempre em locais alagados. Flor rosa.",
    "description": "Vereda."
  },
  {
    "id": "331",
    "scientificName": "Davilla elliptica",
    "popularNames": ["Lixa-de-vaqueiro"],
    "family": "Dilleniaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha extremamente áspera. Flores amarelas.",
    "description": "Cerrado."
  },
  {
    "id": "332",
    "scientificName": "Curatella americana",
    "popularNames": ["Lixeira"],
    "family": "Dilleniaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Ondulada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco tortuoso. Folha lixa grossa.",
    "description": "Pirofítica."
  },
  {
    "id": "333",
    "scientificName": "Doliocarpus dentatus",
    "popularNames": ["Cipó-d'água"],
    "family": "Dilleniaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Transparente (Água)",
    "spines": false,
    "specialFeatures": "Fornece água potável ao cortar o caule.",
    "description": "Mata."
  },
  {
    "id": "334",
    "scientificName": "Roupala montana",
    "popularNames": ["Carne-de-vaca"],
    "family": "Proteaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Variável",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Heterofilia forte. Cheiro ruim.",
    "description": "Mata/Cerrado."
  },
  {
    "id": "335",
    "scientificName": "Euplassa inaequalis",
    "popularNames": ["Carvalho-brasileiro"],
    "family": "Proteaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas coriáceas, ferrugíneas.",
    "description": "Mata."
  },
  {
    "id": "336",
    "scientificName": "Grevillea robusta",
    "popularNames": ["Grevílea"],
    "family": "Proteaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas parecem samambaia, prateadas embaixo.",
    "description": "Exótica."
  },
  {
    "id": "337",
    "scientificName": "Hymenaea courbaril",
    "popularNames": ["Jatobá"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Dois folíolos. Fruto duro com farinha.",
    "description": "Grande porte."
  },
  {
    "id": "338",
    "scientificName": "Hymenaea stigonocarpa",
    "popularNames": ["Jatobá-do-cerrado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Menor que o H. courbaril. Folhas arredondadas.",
    "description": "Cerrado."
  },
  {
    "id": "339",
    "scientificName": "Copaifera langsdorffii",
    "popularNames": ["Copaíba"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Óleo)",
    "spines": false,
    "specialFeatures": "Óleo medicinal no tronco. Pontuações translúcidas.",
    "description": "Mata/Cerradão."
  },
  {
    "id": "340",
    "scientificName": "Dimorphandra mollis",
    "popularNames": ["Fava-d'anta"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Vagens achatadas pretas. Botões tipo espigas.",
    "description": "Medicinal (rutina)."
  },
  {
    "id": "341",
    "scientificName": "Stryphnodendron adstringens",
    "popularNames": ["Barbatimão"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Casca rugosa (jacaré). Medicinal potente.",
    "description": "Cicatrizante."
  },
  {
    "id": "342",
    "scientificName": "Stryphnodendron polyphyllum",
    "popularNames": ["Barbatimão-miúdo"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos minúsculos (menor que adstringens).",
    "description": "Cerrado."
  },
  {
    "id": "343",
    "scientificName": "Anadenanthera colubrina",
    "popularNames": ["Angico-branco"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Amarelo (Goma)",
    "spines": true,
    "specialFeatures": "Tronco liso ou com mamilos. Goma amarela.",
    "description": "Mata seca."
  },
  {
    "id": "344",
    "scientificName": "Anadenanthera peregrina",
    "popularNames": ["Angico-vermelho"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Amarelo (Goma)",
    "spines": false,
    "specialFeatures": "Casca verrucosa, não lisa.",
    "description": "Semidecídua."
  },
  {
    "id": "345",
    "scientificName": "Plathymenia reticulata",
    "popularNames": ["Vinhático"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos retangulares. Madeira amarela.",
    "description": "Mata."
  },
  {
    "id": "346",
    "scientificName": "Machaerium opacum",
    "popularNames": ["Jacarandá-do-cerrado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Vermelho",
    "spines": true,
    "specialFeatures": "Exsudato vermelho. Estípulas espinhosas.",
    "description": "Cerrado."
  },
  {
    "id": "347",
    "scientificName": "Machaerium acutifolium",
    "popularNames": ["Jacarandá-bico-de-pato"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Vermelho",
    "spines": true,
    "specialFeatures": "Folíolos agudos. Espinhos.",
    "description": "Mata."
  },
  {
    "id": "348",
    "scientificName": "Dalbergia miscolobium",
    "popularNames": ["Jacarandá-caviúna"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos emarginados. Fruto sâmara marrom.",
    "description": "Madeira nobre."
  },
  {
    "id": "349",
    "scientificName": "Pterodon emarginatus",
    "popularNames": ["Sucupira-branca"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Óleo",
    "spines": false,
    "specialFeatures": "Fruto sâmara com asa grossa e núcleo de óleo.",
    "description": "Medicinal."
  },
  {
    "id": "350",
    "scientificName": "Bowdichia virgilioides",
    "popularNames": ["Sucupira-preta"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Casca 'quadriculada'. Sementes vermelhas.",
    "description": "Cerrado."
  },
  {
    "id": "351",
    "scientificName": "Vatairea macrocarpa",
    "popularNames": ["Angeliero"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto sâmara gigante (tamanho mão).",
    "description": "Cerradão."
  },
  {
    "id": "352",
    "scientificName": "Andira vermifuga",
    "popularNames": ["Angelim-amargoso"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos opostos na raque. Fruto drupa.",
    "description": "Mata."
  },
  {
    "id": "353",
    "scientificName": "Dipteryx alata",
    "popularNames": ["Baru"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Raquis alada. Semente comestível (castanha).",
    "description": "Fruto duro."
  },
  {
    "id": "354",
    "scientificName": "Platypodium elegans",
    "popularNames": ["Amendoim-bravo"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto sâmara grande torcida. Tronco fenestrado.",
    "description": "Mata."
  },
  {
    "id": "355",
    "scientificName": "Sweetia fruticosa",
    "popularNames": ["Sucupira-amarela"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos alternos na raque.",
    "description": "Mata ciliar."
  },
  {
    "id": "356",
    "scientificName": "Acosmium dasycarpum",
    "popularNames": ["Perobinha"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos pequenos e muitos. Inflorescência branca.",
    "description": "Cerrado."
  },
  {
    "id": "357",
    "scientificName": "Ormosia arborea",
    "popularNames": ["Olho-de-cabra"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Semente bicolor vermelha e preta.",
    "description": "Mata."
  },
  {
    "id": "358",
    "scientificName": "Zeyheria tuberculosa",
    "popularNames": ["Ipê-felpudo"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto bolsa com pelos ásperos.",
    "description": "Mata."
  },
  {
    "id": "359",
    "scientificName": "Zeyheria montana",
    "popularNames": ["Bolsa-de-pastor"],
    "family": "Bignoniaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto redondo achatado.",
    "description": "Cerrado."
  },
  {
    "id": "360",
    "scientificName": "Cybistax antisyphilitica",
    "popularNames": ["Ipê-verde"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor verde. Folíolos menores.",
    "description": "Cerrado."
  },
  {
    "id": "361",
    "scientificName": "Tabebuia aurea",
    "popularNames": ["Ipê-amarelo-do-cerrado"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco suberoso grosso. Folhas prateadas.",
    "description": "Cerrado típico."
  },
  {
    "id": "362",
    "scientificName": "Handroanthus ochraceus",
    "popularNames": ["Ipê-amarelo-cascudo"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas com tomento ocre na face inferior.",
    "description": "Cerrado/Mata."
  },
  {
    "id": "363",
    "scientificName": "Handroanthus impetiginosus",
    "popularNames": ["Ipê-roxo"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos grandes, margem serreada.",
    "description": "Mata."
  },
  {
    "id": "364",
    "scientificName": "Handroanthus serratifolius",
    "popularNames": ["Ipê-amarelo"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Ipê de madeira nobre. Folha verde escura.",
    "description": "Mata alta."
  },
  {
    "id": "365",
    "scientificName": "Jacaranda cuspidifolia",
    "popularNames": ["Jacarandá-caroba"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos terminando em ponta fina. Flor azul.",
    "description": "Cerradão."
  },
  {
    "id": "366",
    "scientificName": "Jacaranda caroba",
    "popularNames": ["Carobinha"],
    "family": "Bignoniaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folíolos coriáceos losangulares.",
    "description": "Cerrado."
  },
  {
    "id": "367",
    "scientificName": "Sparattosperma leucanthum",
    "popularNames": ["Cinco-folhas"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "5 folíolos. Flor branca pintada de rosa.",
    "description": "Pioneira."
  },
  {
    "id": "368",
    "scientificName": "Aspidosperma subincanum",
    "popularNames": ["Guatambu-vermelho"],
    "family": "Apocynaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "specialFeatures": "Face inferior da folha branca. Fruto com lenticelas.",
    "description": "Mata seca."
  },
  {
    "id": "369",
    "scientificName": "Physocalymma scaberrimum",
    "popularNames": ["Cega-machado"],
    "family": "Lythraceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha muito áspera (lixa grossa). Flor roxa.",
    "description": "Madeira duríssima."
  },
  {
    "id": "370",
    "scientificName": "Lafoensia pacari",
    "popularNames": ["Pacari"],
    "family": "Lythraceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Poro subapical na folha.",
    "description": "Medicinal."
  },
  {
    "id": "371",
    "scientificName": "Qualea grandiflora",
    "popularNames": ["Pau-terra-grande"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Estípula com glândula (ponto preto). Flor amarela.",
    "description": "Cerrado."
  },
  {
    "id": "372",
    "scientificName": "Qualea parviflora",
    "popularNames": ["Pau-terra-miúdo"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor roxa pequena. Tronco descamante.",
    "description": "Cerrado."
  },
  {
    "id": "373",
    "scientificName": "Qualea multiflora",
    "popularNames": ["Pau-terra-liso"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Tronco liso claro. Flor amarela.",
    "description": "Cerradão."
  },
  {
    "id": "374",
    "scientificName": "Salvertia convallariodora",
    "popularNames": ["Colher-de-vaqueiro"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Verticilada",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas verticiladas obovadas grandes.",
    "description": "Cerrado."
  },
  {
    "id": "375",
    "scientificName": "Vochysia thyrsoidea",
    "popularNames": ["Gomeira"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Verticilada",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Amarelo (Goma)",
    "spines": false,
    "specialFeatures": "Goma amarela no tronco. Nervura amarela.",
    "description": "Campo rupestre."
  },
  {
    "id": "376",
    "scientificName": "Baccharis platypoda",
    "popularNames": ["Carqueja-amarga"],
    "family": "Asteraceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Caule alado largo plano (parece folha).",
    "description": "Rupestre."
  },
  {
    "id": "377",
    "scientificName": "Eremanthus incanus",
    "popularNames": ["Candeia"],
    "family": "Asteraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas cinzas aveludadas. Flores terminais.",
    "description": "Pioneira rochas."
  },
  {
    "id": "378",
    "scientificName": "Lessingianthus bardanoides",
    "popularNames": ["Bola-de-fogo"],
    "family": "Asteraceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serrilhada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Inflorescência rosa choque grande no chão.",
    "description": "Pós-fogo."
  },
  {
    "id": "379",
    "scientificName": "Piptocarpha rotundifolia",
    "popularNames": ["Coraçao-de-negro"],
    "family": "Asteraceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas redondas duras brancas embaixo.",
    "description": "Cerrado."
  },
  {
    "id": "380",
    "scientificName": "Miconia albicans",
    "popularNames": ["Folha-branca"],
    "family": "Melastomataceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Face inferior totalmente branca.",
    "description": "Muito comum."
  },
  {
    "id": "381",
    "scientificName": "Miconia ferruginata",
    "popularNames": ["Miconia-ferrugem"],
    "family": "Melastomataceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Face inferior cor de ferrugem.",
    "description": "Cerrado."
  },
  {
    "id": "382",
    "scientificName": "Microlicia fasciculata",
    "popularNames": ["Alecrim-dourado"],
    "family": "Melastomataceae",
    "type": "Subarbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "specialFeatures": "Folhas minúsculas resinosas. Flor amarela.",
    "description": "Rupestre."
  },
  {
    "id": "383",
    "scientificName": "Tibouchina stenocarpa",
    "popularNames": ["Quaresmeira-do-brejo"],
    "family": "Melastomataceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas seríceas prateadas. Flor roxa.",
    "description": "Vereda."
  },
  {
    "id": "384",
    "scientificName": "Trembleya laniflora",
    "popularNames": ["Quaresmeira-branca"],
    "family": "Melastomataceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor branca e rosa. Arbusto alto.",
    "description": "Rupestre."
  },
  {
    "id": "385",
    "scientificName": "Eugenia bimarginata",
    "popularNames": ["Pitanga-do-campo"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Nervura marginal dupla visível contra a luz.",
    "description": "Cerrado."
  },
  {
    "id": "386",
    "scientificName": "Eugenia livida",
    "popularNames": ["Eugênia"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas duras verde-escuras.",
    "description": "Cerrado."
  },
  {
    "id": "387",
    "scientificName": "Myrcia bella",
    "popularNames": ["Myrcia"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Inflorescência ampla branca.",
    "description": "Cerrado."
  },
  {
    "id": "388",
    "scientificName": "Psidium grandifolium",
    "popularNames": ["Araçá-comprido"],
    "family": "Myrtaceae",
    "type": "Subarbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas sésseis grandes e rígidas.",
    "description": "Campo."
  },
  {
    "id": "389",
    "scientificName": "Tocoyena formosa",
    "popularNames": ["Jenipapo-de-cavalo"],
    "family": "Rubiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor amarela perfumada. Fruto verde duro.",
    "description": "Cerrado."
  },
  {
    "id": "390",
    "scientificName": "Alibertia edulis",
    "popularNames": ["Marmelada"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Falsa estípula terminal. Fruto preto.",
    "description": "Comestível."
  },
  {
    "id": "391",
    "scientificName": "Genipa americana",
    "popularNames": ["Jenipapo"],
    "family": "Rubiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas grandes. Fruto grande marrom.",
    "description": "Mata ciliar."
  },
  {
    "id": "392",
    "scientificName": "Coutarea hexandra",
    "popularNames": ["Quina-do-cerrado"],
    "family": "Rubiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor branca/rosa assimétrica grande.",
    "description": "Medicinal amarga."
  },
  {
    "id": "393",
    "scientificName": "Rudgea viburnoides",
    "popularNames": ["Congonha-de-bugre"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Estípula 'fimbriada' interpeciolar.",
    "description": "Cerrado."
  },
  {
    "id": "394",
    "scientificName": "Erythroxylum deciduum",
    "popularNames": ["Cocão"],
    "family": "Erythroxylaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Perde folhas na seca. Fruto vermelho.",
    "description": "Mata."
  },
  {
    "id": "395",
    "scientificName": "Byrsonima coccolobifolia",
    "popularNames": ["Murici-rosa"],
    "family": "Malpighiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas arredondadas rígidas (orelha).",
    "description": "Cerrado aoreia."
  },
  {
    "id": "396",
    "scientificName": "Byrsonima verbascifolia",
    "popularNames": ["Murici-cascudo"],
    "family": "Malpighiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folhas aveludadas grandes orelhas de burro.",
    "description": "Campo sujo."
  },
  {
    "id": "397",
    "scientificName": "Byrsonima basiloba",
    "popularNames": ["Murici-do-campo"],
    "family": "Malpighiaceae",
    "type": "Subarbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Rente ao chão. Folhas coriáceas.",
    "description": "Areno."
  },
  {
    "id": "398",
    "scientificName": "Peixotoa tomentosa",
    "popularNames": ["Cipó-de-ouro"],
    "family": "Malpighiaceae",
    "type": "Liana",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Flor amarela vistosa. Estípula cordial.",
    "description": "Liana."
  },
  {
    "id": "399",
    "scientificName": "Davilla rugosa",
    "popularNames": ["Cipó-caboclo"],
    "family": "Dilleniaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Folha áspera. Fruto que abre.",
    "description": "Mata."
  },
  {
    "id": "400",
    "scientificName": "Annona crassiflora",
    "popularNames": ["Araticum"],
    "family": "Annonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "specialFeatures": "Fruto grande marrom 'pinha'. Folhas aveludadas.",
    "description": "Símbolo cerrado."
  }
];