// db_part4.js - Expansão Final para 600 espécies
export const speciesDataPart4 = [
  {
    "id": "501",
    "scientificName": "Tibouchina mutabilis",
    "popularNames": ["Quaresmeira-manacá"],
    "family": "Melastomataceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca/Roxa",
    "specialFeatures": "Flores mudam de cor conforme a maturação.",
    "description": "Espécie ornamental da Mata Atlântica."
  },
  {
    "id": "502",
    "scientificName": "Handroanthus albus",
    "popularNames": ["Ipê-amarelo-da-serra"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Folhas com pilosidade densa e flores amarelas vibrantes.",
    "description": "Muito comum em áreas de altitude."
  },
  {
    "id": "503",
    "scientificName": "Erythrina crista-galli",
    "popularNames": ["Corticeira-do-banhado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "flowerColor": "Vermelha",
    "specialFeatures": "Presença de acúleos no pecíolo e ramos.",
    "description": "Típica de solos encharcados."
  },
  {
    "id": "504",
    "scientificName": "Bauhinia variegata",
    "popularNames": ["Pata-de-vaca-lilás"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Lilás",
    "specialFeatures": "Folha bilobada característica do gênero.",
    "description": "Ampla utilização urbana."
  },
  {
    "id": "505",
    "scientificName": "Calliandra harrisii",
    "popularNames": ["Esponjinha-vermelha"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Vermelha",
    "specialFeatures": "Estames longos e vermelhos em forma de pompom.",
    "description": "Cerrado e áreas abertas."
  },
  {
    "id": "506",
    "scientificName": "Allamanda cathartica",
    "popularNames": ["Alamanda-amarela"],
    "family": "Apocynaceae",
    "type": "Liana",
    "leafArrangement": "Verticilada",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Látex abundante e tóxico.",
    "description": "Trepadeira vigorosa."
  },
  {
    "id": "507",
    "scientificName": "Buchenavia tetraphylla",
    "popularNames": ["Mirindiba"],
    "family": "Combretaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Verde",
    "specialFeatures": "Folhas obovadas aglomeradas no ápice.",
    "description": "Mata Atlântica."
  },
  {
    "id": "508",
    "scientificName": "Tabebuia roseoalba",
    "popularNames": ["Ipê-branco"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Floração curta e intensa no inverno.",
    "description": "Decídua."
  },
  {
    "id": "509",
    "scientificName": "Senna alata",
    "popularNames": ["Mangerioba-do-pará"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Paripinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Inflorescência em espiga ereta.",
    "description": "Medicinal."
  },
  {
    "id": "510",
    "scientificName": "Pachira aquatica",
    "popularNames": ["Munguba"],
    "family": "Malvaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca/Creme",
    "specialFeatures": "Fruto grande lenhoso com sementes comestíveis.",
    "description": "Zonas úmidas."
  },
  {
    "id": "511",
    "scientificName": "Caryocar brasiliense",
    "popularNames": ["Pequi"],
    "family": "Caryocaraceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Crenada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Fruto icônico do Cerrado com espinhos internos.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "512",
    "scientificName": "Byrsonima basiloba",
    "popularNames": ["Murici-cascudo"],
    "family": "Malpighiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Folhas coriáceas com pilosidade ferrugínea.",
    "description": "Frequente em áreas degradadas de Cerrado."
  },
  {
    "id": "513",
    "scientificName": "Kielmeyera coriacea",
    "popularNames": ["Pau-santo"],
    "family": "Calophyllaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Amarelo (Látex)",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Tronco suberoso e látex amarelado.",
    "description": "Cerrado típico."
  },
  {
    "id": "514",
    "scientificName": "Annona crassiflora",
    "popularNames": ["Araticum-do-cerrado"],
    "family": "Annonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Marrom/Creme",
    "specialFeatures": "Fruto grande, doce e muito apreciado pela fauna.",
    "description": "Cerrado sensu stricto."
  },
  {
    "id": "515",
    "scientificName": "Qualea grandiflora",
    "popularNames": ["Pau-terra-do-cerrado"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Casca que se solta em placas; folhas grandes.",
    "description": "Cerrado e cerradão."
  },
  {
    "id": "516",
    "scientificName": "Machaerium opacum",
    "popularNames": ["Jacarandá-do-cerrado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Vermelho",
    "spines": false,
    "flowerColor": "Roxa",
    "specialFeatures": "Seiva vermelha intensa ao corte.",
    "description": "Cerradão e matas secas."
  },
  {
    "id": "517",
    "scientificName": "Enterolobium contortisiliquum",
    "popularNames": ["Orelha-de-negro", "Tamboril"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Fruto em forma de orelha, madeira leve.",
    "description": "Florestas estacionais."
  },
  {
    "id": "518",
    "scientificName": "Hymenaea stigonocarpa",
    "popularNames": ["Jatobá-do-cerrado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Folhas rígidas, fruto lenhoso com polpa farinácea.",
    "description": "Campo cerrado e cerradão."
  },
  {
    "id": "519",
    "scientificName": "Bowdichia virgilioides",
    "popularNames": ["Sucupira-preta"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Roxa",
    "specialFeatures": "Tronco fissurado, flores roxas exuberantes.",
    "description": "Típica de solos pobres do Cerrado."
  },
  {
    "id": "520",
    "scientificName": "Stryphnodendron adstringens",
    "popularNames": ["Barbatimão"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela/Creme",
    "specialFeatures": "Casca rugosa e muito medicinal.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "521",
    "scientificName": "Dimorphandra mollis",
    "popularNames": ["Faveiro"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela/Verde",
    "specialFeatures": "Folhas densamente pilosas; fruto tóxico para gado.",
    "description": "Cerrado."
  },
  {
    "id": "522",
    "scientificName": "Lafoensia pacari",
    "popularNames": ["Pacari"],
    "family": "Lythraceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Folhas brilhosas, tronco liso claro.",
    "description": "Cerradão e matas ciliares."
  },
  {
    "id": "523",
    "scientificName": "Terminalia argentea",
    "popularNames": ["Capitão-do-campo"],
    "family": "Combretaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Tronco profundamente sulcado e folhas prateadas.",
    "description": "Cerradão."
  },
  {
    "id": "524",
    "scientificName": "Vochysia thyrsoidea",
    "popularNames": ["Gomeira"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Verticilada",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Inflorescência terminal amarela muito longa.",
    "description": "Campos rupestres e Cerrado."
  },
  {
    "id": "525",
    "scientificName": "Eriotheca pubescens",
    "popularNames": ["Paineira-do-cerrado"],
    "family": "Malvaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Tronco liso, fruto com paina marrom.",
    "description": "Cerrado sensu stricto."
  },
  {
    "id": "526",
    "scientificName": "Didymopanax macrocarpum",
    "popularNames": ["Mandiocão"],
    "family": "Araliaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Verde",
    "specialFeatures": "Folhas discolores, prateadas na face inferior.",
    "description": "Cerrado e campos."
  },
  {
    "id": "527",
    "scientificName": "Aspidosperma tomentosum",
    "popularNames": ["Peroba-do-campo"],
    "family": "Apocynaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "flowerColor": "Creme",
    "specialFeatures": "Folhas densamente tomentosas (pilosas).",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "528",
    "scientificName": "Callisthene major",
    "popularNames": ["Tapicuru"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Roxa/Branca",
    "specialFeatures": "Folhas pequenas, tronco descamante.",
    "description": "Cerradão e matas."
  },
  {
    "id": "529",
    "scientificName": "Physocalymma scaberrimum",
    "popularNames": ["Cega-machado"],
    "family": "Lythraceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Rosa",
    "specialFeatures": "Madeira extremamente dura, florada rosa intensa.",
    "description": "Cerradão e matas secas."
  },
  {
    "id": "530",
    "scientificName": "Piptadenia gonoacantha",
    "popularNames": ["Pau-jacaré"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "flowerColor": "Branca",
    "specialFeatures": "Tronco com cristas longitudinais espinhosas.",
    "description": "Pioneira de mata ciliar."
  },
  {
    "id": "531",
    "scientificName": "Zeyheria montana",
    "popularNames": ["Bolsa-de-pastor"],
    "family": "Bignoniaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Laranja",
    "specialFeatures": "Fruto circular chato, folhas aveludadas.",
    "description": "Campo cerrado."
  },
  {
    "id": "532",
    "scientificName": "Dalbergia miscolobium",
    "popularNames": ["Jacarandá-do-cerrado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Roxa",
    "specialFeatures": "Folíolos azulados, madeira de alta qualidade.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "533",
    "scientificName": "Anadenanthera falcata",
    "popularNames": ["Angico-do-cerrado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca/Creme",
    "specialFeatures": "Casca suberosa grossa, raque foliar tortuosa.",
    "description": "Cerrado sensu stricto."
  },
  {
    "id": "534",
    "scientificName": "Acosmium dasycarpum",
    "popularNames": ["Chapa-chapinha"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Folhas com brilho metálico na face superior.",
    "description": "Cerrado típico."
  },
  {
    "id": "535",
    "scientificName": "Plathymenia reticulata",
    "popularNames": ["Vinhaático"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Madeira amarelada, casca descamante.",
    "description": "Cerradão e matas."
  },
  {
    "id": "536",
    "scientificName": "Casearia sylvestris",
    "popularNames": ["Guaçatunga"],
    "family": "Salicaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Pontuações translúcidas nas folhas (ver contra luz).",
    "description": "Ocorrendo em quase todos os biomas."
  },
  {
    "id": "537",
    "scientificName": "Protium heptaphyllum",
    "popularNames": ["Almécega"],
    "family": "Burseraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "flowerColor": "Verde",
    "specialFeatures": "Resina branca aromática cicatrizante.",
    "description": "Cerradão e mata ciliar."
  },
  {
    "id": "538",
    "scientificName": "Xylopia aromatica",
    "popularNames": ["Pimenta-de-macaco"],
    "family": "Annonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Ramos dísticos (em plano horizontal).",
    "description": "Cerrado e matas."
  },
  {
    "id": "539",
    "scientificName": "Ouratea hexasperma",
    "popularNames": ["Vassourinha-do-cerrado"],
    "family": "Ochnaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Folhas brilhosas, rígidas e serrilhadas.",
    "description": "Cerrado sensu stricto."
  },
  {
    "id": "540",
    "scientificName": "Luehea paniculata",
    "popularNames": ["Açoita-cavalo-miúdo"],
    "family": "Malvaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Folhas discolores com base assimétrica.",
    "description": "Cerradão e matas ciliares."
  },
  {
    "id": "541",
    "scientificName": "Myrcia guianensis",
    "popularNames": ["Pedra-ume"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Folhas aromáticas, casca fina que solta tiras.",
    "description": "Cerrado e matas."
  },
  {
    "id": "542",
    "scientificName": "Curatella americana",
    "popularNames": ["Lixeira"],
    "family": "Dilleniaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Creme",
    "specialFeatures": "Folhas extremamente ásperas (usadas como lixa).",
    "description": "Cerrado típico."
  },
  {
    "id": "543",
    "scientificName": "Tabebuia aurea",
    "popularNames": ["Ipê-amarelo-do-cerrado", "Paratudo"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Folhas azuladas, tronco suberoso, decídua.",
    "description": "Cerrado e Pantanal."
  },
  {
    "id": "544",
    "scientificName": "Siphoneugena densiflora",
    "popularNames": ["Maria-preta"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Frutos roxo-escuros apreciados por aves.",
    "description": "Cerradão e matas ciliares."
  },
  {
    "id": "545",
    "scientificName": "Cecropia pachystachya",
    "popularNames": ["Embaúba-branca"],
    "family": "Urticaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Creme",
    "specialFeatures": "Tronco oco com divisões internas, pioneira.",
    "description": "Áreas de clareira e beira de mata."
  },
  {
    "id": "546",
    "scientificName": "Alibertia edulis",
    "popularNames": ["Marmelada-nativa"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Fruto comestível globoso preto.",
    "description": "Cerrado e matas."
  },
  {
    "id": "547",
    "scientificName": "Cordiera sessilis",
    "popularNames": ["Marmelinho"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Pequeno arbusto com fruto sésil.",
    "description": "Cerrado sensu stricto."
  },
  {
    "id": "548",
    "scientificName": "Palicourea rigida",
    "popularNames": ["Bate-caixa"],
    "family": "Rubiaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela/Vermelha",
    "specialFeatures": "Folhas rígidas e coriáceas, flores amarelas.",
    "description": "Cerrado típico."
  },
  {
    "id": "549",
    "scientificName": "Bredemeyera floribunda",
    "popularNames": ["Mata-pasto"],
    "family": "Polygalaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Trepadeira lenhosa com raízes medicinais.",
    "description": "Cerrado e matas."
  },
  {
    "id": "550",
    "scientificName": "Vatairea macrocarpa",
    "popularNames": ["Angelim-do-cerrado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Roxa",
    "specialFeatures": "Folíolos com estípulas evidentes.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "551",
    "scientificName": "Sweetia fruticosa",
    "popularNames": ["Perobinha"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Copa globosa e densa, madeira pesada.",
    "description": "Cerrado e campos."
  },
  {
    "id": "552",
    "scientificName": "Handroanthus serratifolius",
    "popularNames": ["Ipê-amarelo-da-mata"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Árvore de grande porte, madeira muito dura.",
    "description": "Matas ciliares e cerradão."
  },
  {
    "id": "553",
    "scientificName": "Piptocarpha rotundifolia",
    "popularNames": ["Coração-de-negro"],
    "family": "Asteraceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Creme",
    "specialFeatures": "Folhas orbiculares e discolores.",
    "description": "Cerrado típico."
  },
  {
    "id": "554",
    "scientificName": "Lamanonia ternata",
    "popularNames": ["Guaraperê"],
    "family": "Cunoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Folíolos denteados, inflorescência globosa.",
    "description": "Matas de altitude e ciliares."
  },
  {
    "id": "555",
    "scientificName": "Stryphnodendron polyphyllum",
    "popularNames": ["Barbatimão-da-folha-miúda"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Creme",
    "specialFeatures": "Folíolos muito pequenos e numerosos.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "556",
    "scientificName": "Zanthoxylum rhoifolium",
    "popularNames": ["Mamica-de-cadela"],
    "family": "Rutaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Crenada",
    "exudate": "Ausente",
    "spines": true,
    "flowerColor": "Branca/Creme",
    "specialFeatures": "Tronco e folhas com acúleos (espinhos).",
    "description": "Cerradão e matas."
  },
  {
    "id": "557",
    "scientificName": "Guazuma ulmifolia",
    "popularNames": ["Mutamba"],
    "family": "Malvaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Folhas com base assimétrica, fruto globoso preto.",
    "description": "Matas ciliares e áreas perturbadas."
  },
  {
    "id": "558",
    "scientificName": "Mimosa scabrella",
    "popularNames": ["Bracatinga"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela/Creme",
    "specialFeatures": "Crescimento rápido, folíolos muito finos.",
    "description": "Mata de altitude (Minas/Sul)."
  },
  {
    "id": "559",
    "scientificName": "Bredemeyera colletioides",
    "popularNames": ["Mata-pasto-miúdo"],
    "family": "Polygalaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Pequenas folhas, ramos muito ramificados.",
    "description": "Cerrado."
  },
  {
    "id": "560",
    "scientificName": "Duguetia furfuracea",
    "popularNames": ["Araticum-de-moita"],
    "family": "Annonaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Vermelha",
    "specialFeatures": "Frutos sincárpicos amarelados, arbusto de cerrado.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "561",
    "scientificName": "Eriosema crinitum",
    "popularNames": ["Eriosema"],
    "family": "Fabaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Densamente piloso (peludo), pequeno porte.",
    "description": "Campo limpo e campo cerrado."
  },
  {
    "id": "562",
    "scientificName": "Cissus sicyoides",
    "popularNames": ["Insulina-vegetal", "Cipó-pucá"],
    "family": "Vitaceae",
    "type": "Liana",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Verde",
    "specialFeatures": "Trepadeira com gavinhas, medicinal.",
    "description": "Matas ciliares."
  },
  {
    "id": "563",
    "scientificName": "Solanum lycocarpum",
    "popularNames": ["Lobeira"],
    "family": "Solanaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Lobada",
    "exudate": "Ausente",
    "spines": true,
    "flowerColor": "Roxa",
    "specialFeatures": "Fruto grande verde consumido pelo lobo-guará.",
    "description": "Cerrado e áreas antropizadas."
  },
  {
    "id": "564",
    "scientificName": "Bauhinia ungulata",
    "popularNames": ["Pata-de-vaca-do-campo"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca/Creme",
    "specialFeatures": "Inflorescência terminal, pétalas estreitas.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "565",
    "scientificName": "Pouteria torta",
    "popularNames": ["Guapeva-do-cerrado"],
    "family": "Sapotaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Branco (Látex)",
    "spines": false,
    "flowerColor": "Verde",
    "specialFeatures": "Ramos tortuosos, látex branco abundante.",
    "description": "Cerradão e cerrado típico."
  },
  {
    "id": "566",
    "scientificName": "Simarouba versicolor",
    "popularNames": ["Pau-paraíba"],
    "family": "Simaroubaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Verde/Branca",
    "specialFeatures": "Folhas brilhosas, casca extremamente amarga.",
    "description": "Cerrado e matas secas."
  },
  {
    "id": "567",
    "scientificName": "Syagrus flexuosa",
    "popularNames": ["Acumã"],
    "family": "Arecaceae",
    "type": "Palmeira",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Palmeira de pequeno porte, estipe solitário ou em touceira.",
    "description": "Cerrado sensu stricto."
  },
  {
    "id": "568",
    "scientificName": "Anacardium humile",
    "popularNames": ["Cajueiro-anão-do-cerrado"],
    "family": "Anacardiaceae",
    "type": "Subarbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "flowerColor": "Rosa/Vermelha",
    "specialFeatures": "Caule subterrâneo (xilopódio) muito desenvolvido.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "569",
    "scientificName": "Campomanesia adamantium",
    "popularNames": ["Guavira"],
    "family": "Myrtaceae",
    "type": "Arbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Fruto amarelo muito doce e perfumado.",
    "description": "Campos e cerrado."
  },
  {
    "id": "570",
    "scientificName": "Coutarea hexandra",
    "popularNames": ["Quina-do-cerrado"],
    "family": "Rubiaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca/Rosa",
    "specialFeatures": "Flores em forma de sino, casca amarga.",
    "description": "Cerradão e matas."
  },
  {
    "id": "571",
    "scientificName": "Diospyros hispida",
    "popularNames": ["Olho-de-boi-do-cerrado"],
    "family": "Ebenaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Creme",
    "specialFeatures": "Folhas pilosas, fruto com indumento ferrugíneo.",
    "description": "Cerrado."
  },
  {
    "id": "572",
    "scientificName": "Gomphrena macrocephala",
    "popularNames": ["Paratudo-do-campo"],
    "family": "Amaranthaceae",
    "type": "Subarbusto",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Vermelha",
    "specialFeatures": "Inflorescência globosa vermelha, raiz medicinal.",
    "description": "Campo limpo."
  },
  {
    "id": "573",
    "scientificName": "Ilex cerasifolia",
    "popularNames": ["Ilex-do-cerrado"],
    "family": "Aquifoliaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Pequenos frutos vermelhos (estilo azevinho).",
    "description": "Cerradão."
  },
  {
    "id": "574",
    "scientificName": "Licania humilis",
    "popularNames": ["Marmelinho-do-campo"],
    "family": "Chrysobalanaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Creme",
    "specialFeatures": "Folhas ásperas e discolores.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "575",
    "scientificName": "Ouratea spectabilis",
    "popularNames": ["Folha-de-serra"],
    "family": "Ochnaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Folhas rígidas, brilhosas com margem serrilhada.",
    "description": "Cerrado e cerradão."
  },
  {
    "id": "576",
    "scientificName": "Peltogyne confertiflora",
    "popularNames": ["Pau-roxo"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Madeira de cor roxa intensa natural.",
    "description": "Mata seca e cerrado."
  },
  {
    "id": "577",
    "scientificName": "Roupala montana",
    "popularNames": ["Carvalho-brasileiro"],
    "family": "Proteaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Creme",
    "specialFeatures": "Folhas com odor de 'queijo' quando maceradas.",
    "description": "Cerrado e matas montanas."
  },
  {
    "id": "578",
    "scientificName": "Siphoneugena widgreniana",
    "popularNames": ["Cambui-do-cerrado"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Copa globosa, pequenos frutos negros.",
    "description": "Cerradão."
  },
  {
    "id": "579",
    "scientificName": "Tapirira guianensis",
    "popularNames": ["Pau-pombo"],
    "family": "Anacardiaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "flowerColor": "Verde/Branca",
    "specialFeatures": "Nervuras secundárias impressas na face superior.",
    "description": "Mata ciliar e cerradão."
  },
  {
    "id": "580",
    "scientificName": "Vochysia cinnamomea",
    "popularNames": ["Canela-de-ema-árvore"],
    "family": "Vochysiaceae",
    "type": "Árvore",
    "leafArrangement": "Verticilada",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Folhas em verticilos, tronco liso amarelado.",
    "description": "Campos rupestres."
  },
  {
    "id": "581",
    "scientificName": "Xylopia sericea",
    "popularNames": ["Pimenta-de-macaco-peluda"],
    "family": "Annonaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Folhas com indumento prateado no verso.",
    "description": "Cerradão e matas ciliares."
  },
  {
    "id": "582",
    "scientificName": "Acacia polyphylla",
    "popularNames": ["Monjoleiro"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "flowerColor": "Branca",
    "specialFeatures": "Muitos acúleos (espinhos) recurvados nos ramos.",
    "description": "Matas ciliares e decíduas."
  },
  {
    "id": "583",
    "scientificName": "Calliandra dysantha",
    "popularNames": ["Flor-de-cerrado"],
    "family": "Fabaceae",
    "type": "Arbusto",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Vermelha",
    "specialFeatures": "Inflorescência em capítulo com estames vermelhos.",
    "description": "Cerrado típico."
  },
  {
    "id": "584",
    "scientificName": "Copaifera langsdorffii",
    "popularNames": ["Copaíba"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Óleo)",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Produz o óleo-resina de copaíba; folíolos brilhosos.",
    "description": "Cerradão e matas."
  },
  {
    "id": "585",
    "scientificName": "Eugenia dysenterica",
    "popularNames": ["Cagaita"],
    "family": "Myrtaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Tronco suberoso e frutos amarelos laxativos.",
    "description": "Cerrado sensu stricto."
  },
  {
    "id": "586",
    "scientificName": "Hymenaea courbaril",
    "popularNames": ["Jatobá-da-mata"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Transparente (Resina)",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Árvore de grande porte, tronco liso cinza.",
    "description": "Matas ciliares e cerradão."
  },
  {
    "id": "587",
    "scientificName": "Machaerium villosum",
    "popularNames": ["Jacarandá-pardo"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Vermelho",
    "spines": false,
    "flowerColor": "Roxa",
    "specialFeatures": "Indumento ferrugíneo (pelos cor de ferrugem) nos ramos.",
    "description": "Matas de Minas e São Paulo."
  },
  {
    "id": "588",
    "scientificName": "Piptadenia viridiflora",
    "popularNames": ["Angico-branco"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": true,
    "flowerColor": "Verde/Creme",
    "specialFeatures": "Casca descamante em placas.",
    "description": "Matas decíduas."
  },
  {
    "id": "589",
    "scientificName": "Salacia crassifolia",
    "popularNames": ["Bacupari-do-cerrado"],
    "family": "Celastraceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Verde",
    "specialFeatures": "Folhas grandes e largas, fruto comestível.",
    "description": "Cerrado sensu stricto."
  },
  {
    "id": "590",
    "scientificName": "Terminalia januarensis",
    "popularNames": ["Capitão-de-januária"],
    "family": "Combretaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Casca fissurada, madeira muito resistente.",
    "description": "Mata seca do Norte de MG."
  },
  {
    "id": "591",
    "scientificName": "Vatairea macrocarpa",
    "popularNames": ["Angelim-do-cerrado"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Roxa",
    "specialFeatures": "Folíolos pubescentes (peludos) e flores roxas.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "592",
    "scientificName": "Buchenavia tetraphylla",
    "popularNames": ["Mirindiba"],
    "family": "Combretaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Amarela",
    "specialFeatures": "Folhas obovadas aglomeradas em rosetas.",
    "description": "Mata Atlântica e matas de galeria."
  },
  {
    "id": "593",
    "scientificName": "Casearia gossypiosperma",
    "popularNames": ["Espeteiro"],
    "family": "Salicaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Sementes envoltas em fibras brancas (estilo algodão).",
    "description": "Mata ciliar e decídua."
  },
  {
    "id": "594",
    "scientificName": "Dalbergia cearensis",
    "popularNames": ["Violeta-do-brasil"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca/Creme",
    "specialFeatures": "Madeira estriada cor de violeta e negra.",
    "description": "Caatinga e matas secas."
  },
  {
    "id": "595",
    "scientificName": "Esenbeckia leiocarpa",
    "popularNames": ["Guarantã"],
    "family": "Rutaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Trifoliolada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Folhas brilhosas, madeira extremamente dura.",
    "description": "Mata Atlântica e matas de Minas."
  },
  {
    "id": "596",
    "scientificName": "Handroanthus heptaphyllus",
    "popularNames": ["Ipê-roxo-da-mata"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Digitada",
    "leafMargin": "Serreada",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Roxa",
    "specialFeatures": "Geralmente com 7 folíolos e flores roxas intensas.",
    "description": "Matas ciliares e cerradão."
  },
  {
    "id": "597",
    "scientificName": "InGA laurina",
    "popularNames": ["Ingá-feijão"],
    "family": "Fabaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Branca",
    "specialFeatures": "Raque foliar sem asa, fruto vagem pequena.",
    "description": "Beira de rios e matas úmidas."
  },
  {
    "id": "598",
    "scientificName": "Jacaranda cuspidifolia",
    "popularNames": ["Jacarandá-caroba"],
    "family": "Bignoniaceae",
    "type": "Árvore",
    "leafArrangement": "Oposta",
    "leafComposition": "Composta Bipinada",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Azul/Roxa",
    "specialFeatures": "Folíolos terminando em ponta fina (cuspidados).",
    "description": "Cerradão e matas secas."
  },
  {
    "id": "599",
    "scientificName": "Licania kunthiana",
    "popularNames": ["Oiti-do-cerrado"],
    "family": "Chrysobalanaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Simples",
    "leafMargin": "Inteira",
    "exudate": "Ausente",
    "spines": false,
    "flowerColor": "Creme",
    "specialFeatures": "Folhas rígidas elípticas, discolores.",
    "description": "Cerrado stricto sensu."
  },
  {
    "id": "600",
    "scientificName": "Zanthoxylum pohlianum",
    "popularNames": ["Mamica-de-cadela-lisa"],
    "family": "Rutaceae",
    "type": "Árvore",
    "leafArrangement": "Alterna",
    "leafComposition": "Composta Pinada",
    "leafMargin": "Crenada",
    "exudate": "Ausente",
    "spines": true,
    "flowerColor": "Creme",
    "specialFeatures": "Acúleos nos ramos, folhas aromáticas cítricas.",
    "description": "Matas ciliares e cerrado."
  }
];